### ISSUE TITLE
example_update_dynamic_dns.py---get dns record is validating only first 20 records of the zone

### ISSUE THREAD

**Issue by tejav9981** [cloudflare/python-cloudflare#102]
Hi ,

Before updating the dns record, to validate the DNS record exists, it is validating only first 20 records and throwing the error with record not found in that particular zone.

Regards,

**Comment by mahtin** [comment]
Oops! Most Cloudflare API's return just 20 records and then expect you to page thru results. This isn't coded into that example, which is bad and should be fixed. I will do that later; however for now, I recommend you change line 37 to something like this ...
```
        params = {'name':dns_name, 'match':'all', 'type':ip_address_type, 'per_page':200}
```
... which will somewhat help; but is (of course) not the real fix. See examples/example_paging_thru_zones.py file for a paging thru zones example using `raw` mode.

However, now that I say this ... I realize the `'match':'all'` could be wrong as it only needs to match `A` or `AAAA` records. 
Let me think about this and play around later.

**Comment by mahtin** [comment]
I can replicate this failure; but only in a mode where this example is not meant to handle. You have to create more than one `A` record for the dns name in order to have this example hiccup. That should not be it's operating mode. Hence I would recommend you clean up the dns records such that your host only has one `A` record before running this example.

**Comment by tejav9981** [comment]
Hi Martin,

Thanks for your response.

Do you have anything for firewall filters and firewall rules examples?

Appreciate your help

Regards,
Laxmiteja
