### ISSUE TITLE
python 3.8 not working

### ISSUE THREAD

**Issue by Diablo2050** [cloudflare/python-cloudflare#113]
when using the code like so:

`import CloudFlare
import os
from dotenv import load_dotenv
load_dotenv()
from pathlib import Path  # python3 only

cf = CloudFlare.CloudFlare(email=os.getenv("EMAIL"), token=os.getenv("AUTH_KEY"))

def main():
    zones = cf.zones.get()
    for zone in zones:
        zone_id = zone['id']
        zone_name = zone['name']
        print(zone_id, zone_name)

if __name__ == '__main__':
    main()`

I get an exception like so:

`Traceback (most recent call last):
  File "/code2/cl.py", line 23, in <module>
    main()
  File "/code2/cl.py", line 16, in main
    zones = cf.zones.get()
  File "/code2/venv/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 672, in get
    return self._base.call_with_auth('GET', self._parts,
  File "/code2/venv/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 126, in call_with_auth
    return self._call(method, headers, parts,
  File "/code2/venv/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 498, in _call
    raise CloudFlareAPIError(code, message, error_chain)
CloudFlare.exceptions.CloudFlareAPIError: Invalid request headers`

**Comment by mahtin** [comment]
First thing first. Take a look at the **Using shell environment variables** section of the [README](https://github.com/cloudflare/python-cloudflare/blob/master/README.md#using-shell-environment-variables) file and you will see that if you use the following environment variables, then you don't need to do the `os.getenv()` calls in your file.
```
$ export CF_API_EMAIL='user@example.com'
$ export CF_API_KEY='00000000000000000000000000000000'
$
```
Now lets get onto the error at hand. Please see the **Providing Cloudflare Username and API Key** section of the [README](https://github.com/cloudflare/python-cloudflare/blob/master/README.md#providing-cloudflare-username-and-api-key) file. If you are using an **API Token** then don't include the `email` in the call. Only include the `token`. This is also explained on the [support page](https://support.cloudflare.com/hc/en-us/articles/200167836-Managing-API-Tokens-and-Keys) from Cloudflare.

Finally, I would recommend following the example at **Using configuration file to store email and keys** in the [README](https://github.com/cloudflare/python-cloudflare/blob/master/README.md#using-configuration-file-to-store-email-and-keys) file so that you can manage this easier. 

Summary: This does not look like a Python 3.8 issue and more like a `token` issue. Remember (as the README's say) you should only pass an `email` value when you are using API keys. When using API tokens, don't pass an `email` value.

You can also set a debug value to should you what's going on. 
```
    cf = CloudFlare.CloudFlare(debug=True)
```

Hope that helps.

**Comment by mahtin** [comment]
This is rolled into #118
