### ISSUE TITLE
cannot get whitelist firewall rules?

### ISSUE THREAD

**Issue by gingerlime** [cloudflare/python-cloudflare#116]
This might not be an issue strictly with the library, but perhaps the Cloudflare API, but I'm hoping someone can still help...

I'm able to get firewall rules with `mode: js_challenge`, but not other modes for some reason ... When I look at the Cloudflare web interface, I have a mix of those, but for some reason not via the API?

![CleanShot 2021-05-04 at 17 27 41](https://user-images.githubusercontent.com/524274/117028994-85b78680-acfe-11eb-90d9-c4100ffd3826.png)

![CleanShot 2021-05-04 at 17 31 29](https://user-images.githubusercontent.com/524274/117029432-ed6dd180-acfe-11eb-9140-b377861aef21.png)

![CleanShot 2021-05-04 at 17 34 45](https://user-images.githubusercontent.com/524274/117029846-59e8d080-acff-11eb-8015-7b948871838f.png)

Any tips or things to try to make it work??

**Comment by mahtin** [comment]
I think you are correct. This isn't a python library issue. According to https://api.cloudflare.com/#user-level-firewall-access-rule-list-access-rules the `mode` value should accept:

> valid values: block, challenge, whitelist, js_challenge

I would recommend popping over to https://community.cloudflare.com and ask there.

However, I did test it with the library (via the CLI command). See the following:

Start with nothing.

```
$ cli4 /user/firewall/access_rules/rules
[]
$
```

Create four firewall access rules

```
$ cli4 --post mode=block configuration='{"target":"ip","value":"33.0.0.1"}' /user/firewall/access_rules/rules
{
    ...
    "created_on": "2021-05-05T04:30:50.907246173Z",
    ...
    "mode": "block",
    ...
}
$ cli3 --post mode=challenge configuration='{"target":"ip","value":"33.0.0.2"}' /user/firewall/access_rules/rules
{
    ...
    "created_on": "2021-05-05T04:31:10.806691187Z",
    ...
    "mode": "challenge",
    ....
}
$ cli4 --post mode=whitelist configuration='{"target":"ip","value":"33.0.0.3"}' /user/firewall/access_rules/rules
{
    ...
    "created_on": "2021-05-05T04:31:24.947826Z",
    ...
    "mode": "whitelist",
    ...
}
$ cli4 --post mode=js_challenge configuration='{"target":"ip","value":"33.0.0.4"}' /user/firewall/access_rules/rules
{
    ...
    "created_on": "2021-05-05T04:31:47.910265834Z",
    ...
    "mode": "js_challenge",
}
$
```

This produces firewall access rules  with all of those values.

```
$ cli4 /user/firewall/access_rules/rules | jq -c '.[]|.created_on,.mode,.configuration' | paste - - - | column -s'  ' -t
"2021-05-05T04:31:47.910265834Z"  "js_challenge"  {"target":"ip","value":"33.0.0.4"}
"2021-05-05T04:31:24.947826Z"     "whitelist"     {"target":"ip","value":"33.0.0.3"}
"2021-05-05T04:31:10.806691187Z"  "challenge"     {"target":"ip","value":"33.0.0.2"}
"2021-05-05T04:30:50.907246173Z"  "block"         {"target":"ip","value":"33.0.0.1"}
$
```

The `mode` search can also be tested.

```
$ for m in block challenge whitelist js_challenge ; do echo ==== $m; cli4 mode=$m /user/firewall/access_rules/rules | jq -c '.[]|.created_on,.mode,.configuration' | paste - - - ; done
==== block
"2021-05-05T04:30:50.907246173Z"        "block" {"target":"ip","value":"33.0.0.1"}
==== challenge
"2021-05-05T04:31:10.806691187Z"        "challenge"     {"target":"ip","value":"33.0.0.2"}
==== whitelist
"2021-05-05T04:31:24.947826Z"   "whitelist"     {"target":"ip","value":"33.0.0.3"}
==== js_challenge
"2021-05-05T04:31:47.910265834Z"        "js_challenge"  {"target":"ip","value":"33.0.0.4"}
$
```

I'm pretty sure this works. Here's the dashboard showing these created firewall access lists.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/4521085/117098044-3a16d400-ad22-11eb-8e64-3dc0d213d01b.png">

Now I clean up - because the above is not wanted on my account.

```
$ cli4 /user/firewall/access_rules/rules | jq -rc '.[]|.id' | while read id ; do cli4 --delete /user/firewall/access_rules/rules/:$id ; done
{
    ...
}
{
    ...
}
{
    ...
}
{
    ...
}
$
```

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/4521085/117098342-08ead380-ad23-11eb-84af-13eb9d4facc7.png">

I hope that helps and gets you somewhere further with your code.

**Comment by gingerlime** [comment]
Thank you! Does it work if you add rules via the Cloudflare web UI? I have a feeling the rules that I get back from the API are only those created via the API ...

**Comment by gingerlime** [comment]
... or perhaps it has to do with the user account? I created some rules via the UI from a different user email (on the same CF account) than the one I use for the API. Although I tried to get the rule with the same email credentials and still cannot list all the rules that I can see on the web UI.

**Comment by gingerlime** [comment]
I tested further and can confirm that:

* when I add a rule via the API, I can also see it when I get the list of rules
* when I add a rule via the Web UI, it's not listed when I retrieve rules from the API

**Comment by mahtin** [comment]
Ah. So your original issue had the **users** based API call in your code. I was going down that path.

There's also an **organizations** based and **zones** based firewall access_rules. I think you want the latter because I think you're editing a firewall access_rules on the Cloudflare dashboard under a zone. So that means you want the **zones** based API call.

Please read the https://api.cloudflare.com/ section on zone based firewall access rules. Then modify your API call to be zones based (you'll pass the zone_id as the first argument). 

I hope that helps.

**Comment by gingerlime** [comment]
Ah, I see. Thank you. This is mighty confusing for me, I have to say... What if I want to query all possible rules (be it user, organization or zone)? I have to query 3 different endpoints to be able to get a definitive list of all the rules?

**Comment by mahtin** [comment]
That is correct. Different usage models exist to satisfy different customers methodology. I recommend you pick your best methodology and stick to it. Don't cross the streams[1] so to speak!

[1] "Don't cross the streams. It would be bad." - Ghostbusters movie

**Comment by gingerlime** [comment]
![image](https://user-images.githubusercontent.com/524274/117174814-67b95700-adce-11eb-8739-199bade3fae2.png)
