### ISSUE TITLE
CloudFlareError does not evaluate to true if there are no chained errors

### ISSUE THREAD

**Issue by apmelton-lambda** [cloudflare/python-cloudflare#182]
Demonstration:

```
from CloudFlare.exceptions import CloudFlareAPIError

if CloudFlareAPIError(999, "foo"):
    print("true")
else:
    print("false")

if CloudFlareAPIError(999, "foo", error_chain=[{"code": 888, "message": "bar"}]):
    print("true")
else:
    print("false")
```

Evaluates to:

```
false
true
```

This is an issue because of how [concurrent.futures handles raising exceptions](https://github.com/python/cpython/blob/main/Lib/concurrent/futures/_base.py#L399). If the `Exception` doesn't evaluate as true, it will incorrectly return the `_result`. You could potentially argue that this is a logic issue in concurrent.futures or a logic issue with `len` and error chains in CloudFlareAPIError. Should `self` be considered part of the error chain? And thus, there's always at least a single error?

**Comment by mahtin** [comment]
Interesting thought. This is the code used to fully decode an exception (which is in itself coming from the API with one or more messages). This comes from `cli4/cli4.py`.
```python
        except CloudFlare.exceptions.CloudFlareAPIError as e:
            if len(e) > 0:
                # more than one error returned by the API
                for x in e:
                    sys.stderr.write('cli4: /%s - %d %s\n' % (command, int(x), str(x)))
            sys.stderr.write('cli4: /%s - %d %s\n' % (command, int(e), str(e)))
```
This works, as does a simple exception (i.e ignoring if more than one error is there). This is from `examples/examples_zones.py`.
```python
        except CloudFlare.exceptions.CloudFlareAPIError as e:
            sys.stderr.write('/zones/dns_records %d %s - api call failed\n' % (e, e))
```
So, ignoring `concurrent.futures`, I think this is ok. However, now you have sent this issue in ... I think it needs addressing. 

Stay tuned. Let me do some research.

**Comment by mahtin** [comment]
I've been testing this patch to the `CloudFlareError` `Exception` class. I can't see any issue with this simple fix:
```python
+    def __bool__(self):
+        """ bool value for Cloudflare API errors"""
+
+        return True
+
```
Based on https://docs.python.org/3/library/stdtypes.html#truth-value-testing and because there's a `__len__` value I think this is the correct and simple fix (independent of `concurrent.futures`). The issue is caused by the Cloudflare python exceptions having a `len()` function which does not exist in the base `Exception` class.

```bash
$ python
...
>>> e = Exception()
>>> len(e)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'Exception' has no len()
>>> ^D
$
```
This does fix your issue above.
```bash
$ python /tmp/issues182.py
true
true
$
```

I'll mull this over for another day or so; but welcome your feedback.

**Comment by mahtin** [comment]
Turns out this is an important fix. I've run a bunch of tests and consulted various knowledgeable sources (stackoverflow, Python doc org, etc). It uncovered some other issues in the `exceptions.py` file when exceptions are re-raised (which makes sense after thinking about that). 

I'm still thinking about the another cleanup that was requested a while ago (moving `evalue` into the `0`'th element of `error_chain` to simplify everything). Now I'm liking that idea more-n-more.

I will say thank you for this issue. It's helped rethink some code structure - beyond your initial issue. Always welcome! 

No new release yet - code freeze because it's Super Bowl Sunday. 🤣

**Comment by apmelton-lambda** [comment]
Of course, and thank you for digging in!

**Comment by mahtin** [comment]
Release `2.18.2` is now pushed with this fix included. The usual `pip install --upgrade cloudflare` will get you all the goodies. Please close the issue if you are happy with this release. - Thanks again for the pointer towards this. - Martin

**Comment by apmelton-lambda** [comment]
Thanks! Just ran a quick test using the new version and I cannot reproduce the issue we were seeing, so I think this is good to go!

**Comment by mahtin** [comment]
Unrelated to your issue; however `2.19.0` is now pushed because of a bad (but unrelated) bug in `2.18.?` within the `cli4` command. Please upgrade.
