### ISSUE TITLE
Unable to update TTL

### ISSUE THREAD

**Issue by DaTurret** [cloudflare/python-cloudflare#63]
If you call cli4 like so:
`python -m cli4 --put name=$record type=A ttl=120 content=$ip /zones/:$domain/dns_records/:$record`
you will get the following error:
`cli4: /zones/:<ZONE_NAME>/dns_records/:<RECORD> - 1004 DNS Validation Error`
Without the TTL Attribute this works fine and returns the Expected Record in JSON Format.

**Comment by mahtin** [comment]
The `ttl` value should be a integer (vs a string). For the `cli4` command you should use `==` in order to force the code to convert to integer. This was in very early code.

However, there's a bug in the library that seems to stop the full error message from displaying. That fix has been pushed. Please upgrade. It's in the `2.5.1` release. See https://pypi.org/project/cloudflare/ for a quick install.

Once upgraded your command will produce a more meaningful error when the `ttl` value is not correct. Here is a failure and a success. Note the difference.

```
$ cli4 --post name='example300' type='A' content='10.0.0.1' ttl=300 /zones/:██████████.com/dns_records
cli4: /zones/:██████████.com/dns_records - 9021 Invalid TTL. Must be between 120 and 2,147,483,647 seconds, or 1 for automatic
cli4: /zones/:██████████.com/dns_records - 1004 DNS Validation Error
$
```

```
$ cli4 --post name='example300' type='A' content='10.0.0.1' ttl==300 /zones/:██████████.com/dns_records
{
    "content": "10.0.0.1",
    ...
    "id": "█████████████████",
    "name": "example300.██████████.com",
    ...
    "ttl": 300,
    "type": "A",
    ...
}
$
```

I hope that helps.
