### ISSUE TITLE
[Question] DNS Zone Import

### ISSUE THREAD

**Issue by rogeriolino** [cloudflare/python-cloudflare#89]
Hi,

I'm trying to call the `dns_records/import` endpoint using this python lib, but I can't find how to do it.

Please someone provide an example (add this one to examples directory).

Regards

**Comment by mahtin** [comment]
There’s an example in the README.md file for the command line user of `cli4` and `dns_records/import`.

To use this in Python use: `r = cf.zones.dns_records.import.post(zone_id, files={‘file’: fd})`

**Comment by rogeriolino** [comment]
Hi @mahtin thanks to reply me (and so fastly)

I've tried to use `post(zone_id, data=fd)` and was getting `connection failed` error, now using `files` as you described, works.

**Comment by rogeriolino** [comment]
Hi @mahtin 

The import messages are being hidden from original response.

Cloudflare API returns messages array filled even if `success` is `True`:

Result using curl

```json
{
  "result": {
    "recs_added": 4,
    "recs_added_by_type": {
      "MX": 1,
      "TXT": 3
    },
    "total_records_parsed": 8
  },
  "success": true,
  "errors": [],
  "messages": [
    {
      "code": 81053,
      "message": "abc.com: An A, AAAA or CNAME record already exists with that host."
    }
  ]
}
```

Result using sdk (raw=False)

```json
{
  "recs_added": 1,
  "recs_added_by_type": {
    "MX": 1
  },
 "total_records_parsed": 8
}
```

Result using sdk (raw=True)

```json
{
  "result": {
    "recs_added": 1,
    "recs_added_by_type": {
      "MX": 1
    },
   "total_records_parsed": 8
  }
}
```

**Comment by skyscooby** [comment]
Does this even work? For whatever reason 2.8.15 doesn't even recognize import as a valid operation on dns_records.. export works tho.
```
>>> r = cf.zones.dns_records.import.post(zone_id, files={‘file’: fd})
  File "<stdin>", line 1
    r = cf.zones.dns_records.import.post(zone_id, files={‘file’: fd})
                             ^
SyntaxError: invalid syntax
```

**Comment by mahtin** [comment]
@skyscooby - you are absolutely correct. While the word `import` is a reserved word in Python; using it via the packages command line program `cli4` works because it's searched in the class dictionary vs used in a python language statement.  I tried your code and it fails.

This is unfortunate and your comment (_Does this even work?_) is in fact correct - the code was never tested (by me) as python code. I only tested the `cli4` version. You can see a working example in the [README](https://github.com/cloudflare/python-cloudflare#zone-file-upload-and-download-cli-examples-uses-bind-format-files) file.

So ... two solutions. The README has the command line example:

```bash
$cli4 --post file=@zone.txt /zones/:example.com/dns_records/import
...
$
```

This does work.

To code this in Python, some shenanigans is needed. This code works. Here is the core work-around for the reserved name issue:

```python
    m = cf.zones.dns_records
    m = getattr(m, 'import')
    r = m.post(zone_id, files={'file':fd})
```

The full example is as follows:

```python
#!/usr/bin/env python
"""Cloudflare API code - example"""

import os
import sys
sys.path.insert(0, os.path.abspath('..'))

import json

import CloudFlare

def main():
    """Cloudflare API code - example"""

    try:
        zone_name = sys.argv[1]
        file_name = sys.argv[2]
    except IndexError:
        exit('usage: example_dns_import.py zone zone-file')

    try:
        fd = open(file_name, 'rb')
    except:
        exit('file open - %s' % (e))

    cf = CloudFlare.CloudFlare()

    # grab the zone identifier
    try:
        params = {'name': zone_name}
        zones = cf.zones.get(params=params)
    except CloudFlare.exceptions.CloudFlareAPIError as e:
        exit('/zones %d %s - api call failed' % (e, e))
    except Exception as e:
        exit('/zones.get - %s - api call failed' % (e))

    if len(zones) == 0:
        exit('/zones.get - %s - zone not found' % (zone_name))

    if len(zones) != 1:
        exit('/zones.get - %s - api call returned %d items' % (zone_name, len(zones)))

    zone_id = zones[0]['id']

    m = cf.zones.dns_records
    m = getattr(m, 'import')

    try:
        r = m.post(zone_id, files={'file':fd})
    except CloudFlare.exceptions.CloudFlareAPIError as e:
        exit('/zones/dns_records/import %s - %d %s - api call failed' % (dns_name, e, e))

    print(json.dumps(r))

    exit(0)

if __name__ == '__main__':
    main()
```

I will add this to both the README and to the `examples` folder.

@skyscooby - Thank you for pointing this out. I will reopen this issue and close once the code is updated.
@rogeriolino - Sorry for completely missing this year - my bad!
