### ISSUE TITLE
please indicate which GPG key is expected to sign pypi releases

### ISSUE THREAD

**Issue by FelixSchwarz** [cloudflare/python-cloudflare#93]
Thank you very much for signing your pypi releases. I'll make sure that the Fedora (+ CentOS/EPEL) RPM build process will verify the source code whenever a new version is built.

However it would be really helpful if there was an indication which GPG key(s) are expected to sign releases (ideally I'd like to retrieve these keys via a HTTPs URL directly).

**Comment by mahtin** [comment]
Great question (and thank you for doing RPM work)!  If you look in [Makefile](https://github.com/cloudflare/python-cloudflare/blob/master/Makefile) you'll see:
```
EMAIL = "mahtin@mahtin.com"
...
upload-pypi:
	$(PYTHON) setup.py -q sdist upload --sign --identity="$(EMAIL)"
```
You can find me on [Keybase](https://keybase.io/mahtin) and confirmation of my fingerprint via my [twitter page](https://twitter.com/mahtin).

**Comment by FelixSchwarz** [comment]
Thank you very much - that works for me :-)

**Comment by FelixSchwarz** [comment]
Thank you for signing the 2.7.1 release. However I noticed that the signing key changed:

    gpgv: Signature made Wed May 13 03:45:20 2020 CEST
    gpgv:                using RSA key D0930FD222203ABF557CA4856112910956F6F8B8
    gpgv:                issuer "martin@cloudflare.com"
    gpgv: Can't check signature: No public key
    gpgverify: Signature verification failed.

Can you confirm that this is the expected GPG key? Would you mind documenting this somewhere (e.g. in `README.md`)?

**Comment by mahtin** [comment]
I'm here ...
   http://keys.gnupg.net/pks/lookup?search=martin%40cloudflare.com&fingerprint=on&op=index
   http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0x6112910956F6F8B8
... and technically on the MIT site; but that site is sadly failing.
  https://pgp.mit.edu/pks/lookup?search=martin%40cloudflare.com&op=index
  https://pgp.mit.edu/pks/lookup?op=get&search=0x6112910956F6F8B8 (FAILS)

I recently updated the `Makefile` to use my work email address - mainly because of this signing. It seemed the right thing to do.

```
$ egrep 'EMAIL ='  Makefile
EMAIL = "mahtin@mahtin.com"
EMAIL = "martin@cloudflare.com"
$
```
The email address is listed on https://pypi.org/project/cloudflare/ in the Author section.  Hopefully that's enough proof for now. I will add an email address and PGP section into the README at a latter point (and drop my home email from the release).

**Comment by FelixSchwarz** [comment]
Yes, that's totally fine. I just did not want to switch key ids without any kind of "official" notice :-)
